const { PrismaClient, EventCategory } = require('@prisma/client')

const prisma = new PrismaClient()

async function main() {
  // Clear existing events
  await prisma.event.deleteMany()

  // Seed events from the spreadsheet
  const events = [
    {
      name: "San Miguel de Allende",
      location: "Guanajuato, Mexico",
      date: new Date("2025-04-17"),
      music: [],
      city: "San Miguel de Allende",
      state: "Guanajuato",
      country: "Mexico",
      startDate: new Date("2025-04-17"),
      endDate: new Date("2025-04-20"),
      description: "Recorre las encantadoras calles empedradas de San Miguel de Allende y maravíllate con la arquitectura colonial de la Parroquia de San Miguel Arcángel.",
      highlights: ["Arquitectura colonial", "Calles empedradas", "Aguas termales"],
      activities: ["Visita a museos", "recorridos culturales", "fotografía", "gastronomía local", "compras de arte y artesanías"],
      category: EventCategory.CULTURAL,
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2650
    },
    {
      name: "CDMX",
      location: "Ciudad de México, Mexico",
      date: new Date("2025-04-24"),
      music: [],
      city: "CDMX",
      state: "Ciudad de México",
      country: "Mexico",
      startDate: new Date("2025-04-24"),
      endDate: new Date("2025-04-27"),
      description: "Explora el imponente Zócalo y visita el Palacio de Bellas Artes, sumergiéndote en la vibrante escena artística y cultural de la capital mexicana.",
      highlights: ["Centro histórico", "Arte y cultura", "Parques urbanos"],
      activities: ["Visita a museos", "turismo histórico", "gastronomía callejera", "fotografía urbana", "tours en bicicleta"],
      category: EventCategory.CULTURAL,
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2800
    },
    {
      name: "San Pedro Martir",
      location: "Baja California, Mexico",
      date: new Date("2025-04-25"),
      music: [],
      city: "San Pedro Martir",
      state: "Baja California",
      country: "Mexico",
      startDate: new Date("2025-04-25"),
      endDate: new Date("2025-04-27"),
      description: "Embárcate en una aventura de senderismo en la Sierra de San Pedro Mártir y visita el Observatorio Astronómico Nacional para una experiencia estelar única.",
      highlights: ["Senderismo de montaña", "Observación astronómica", "Vida silvestre"],
      activities: ["Senderismo", "observación astronómica", "camping", "fotografía de naturaleza", "avistamiento de fauna"],
      category: EventCategory.NATURE,
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2720
    },
    {
      name: "La Paz",
      location: "Baja California Sur, Mexico",
      date: new Date("2025-05-01"),
      music: [],
      city: "La Paz",
      state: "Baja California Sur",
      country: "Mexico",
      startDate: new Date("2025-05-01"),
      endDate: new Date("2025-05-04"),
      description: "Nada junto al majestuoso tiburón ballena en las aguas cristalinas de La Paz y relájate en las tranquilas playas de Balandra.",
      highlights: ["Playas vírgenes", "Nado con fauna marina", "Paseos en lancha"],
      activities: ["Snorkel", "kayak", "nado con fauna marina", "fotografía de paisajes", "paseo en bote"],
      category: EventCategory.BEACH,
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2900
    },
    {
      name: "Chihuahua",
      location: "Chihuahua, Mexico",
      date: new Date("2025-05-09"),
      music: [],
      city: "Chihuahua",
      state: "Chihuahua",
      country: "Mexico",
      startDate: new Date("2025-05-09"),
      endDate: new Date("2025-05-12"),
      description: "Viaja en el legendario tren 'El Chepe' a través de las impresionantes Barrancas del Cobre y descubre la riqueza cultural de la Sierra Tarahumara.",
      highlights: ["Cañones impresionantes", "Rutas escénicas en tren", "Cultura indígena"],
      activities: ["Senderismo", "recorridos en tren turístico", "visita a museos", "fotografía de paisajes", "turismo histórico"],
      category: EventCategory.ADVENTURE,
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2670
    },
    {
      name: "Riviera Nayarit",
      location: "Nayarit, Mexico",
      date: new Date("2025-05-15"),
      music: [],
      city: "Riviera Nayarit",
      state: "Nayarit",
      country: "Mexico",
      startDate: new Date("2025-05-15"),
      endDate: new Date("2025-05-18"),
      description: "Surfea las olas de Sayulita y explora las Islas Marietas, hogar de la famosa Playa Escondida.",
      highlights: ["Playas paradisíacas", "Surf y deportes acuáticos", "Pueblos costeros"],
      activities: ["Surf", "avistamiento de ballenas", "caminatas por la playa", "fotografía", "actividades acuáticas"],
      category: EventCategory.BEACH,
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2750
    },
    {
      name: "Hidalgo",
      location: "Hidalgo, Mexico",
      date: new Date("2025-05-22"),
      music: [],
      city: "Hidalgo",
      state: "Hidalgo",
      country: "Mexico",
      startDate: new Date("2025-05-22"),
      endDate: new Date("2025-05-25"),
      description: "Sumérgete en las aguas termales de las Grutas de Tolantongo y maravíllate con los Prismas Basálticos, formaciones geológicas únicas en su tipo.",
      highlights: ["Aguas termales", "Formaciones geológicas", "Pueblos tradicionales"],
      activities: ["Aguas termales", "senderismo", "fotografía de naturaleza", "visita a pueblos mágicos", "gastronomía regional"],
      category: EventCategory.NATURE,
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2600
    },
    {
      name: "Loreto",
      location: "Baja California Sur, Mexico",
      date: new Date("2025-06-03"),
      music: [],
      city: "Loreto",
      state: "Baja California Sur",
      country: "Mexico",
      startDate: new Date("2025-06-03"),
      endDate: new Date("2025-06-06"),
      description: "Navega por el Parque Nacional Bahía de Loreto y practica snorkel entre la diversa vida marina del 'Aquarium of the World'.",
      highlights: ["Playas tranquilas", "Snorkel y buceo", "Avistamiento de fauna marina"],
      activities: ["Snorkel", "senderismo", "observación de ballenas", "fotografía marina", "visitas culturales"],
      category: EventCategory.BEACH,
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2700
    },
    {
      name: "Jalisco",
      location: "Jalisco, Mexico",
      date: new Date("2025-06-12"),
      music: [],
      city: "Jalisco",
      state: "Jalisco",
      country: "Mexico",
      startDate: new Date("2025-06-12"),
      endDate: new Date("2025-06-15"),
      description: "Recorre los campos de agave en Tequila y disfruta de una cata en una destilería tradicional, descubriendo los secretos de esta emblemática bebida mexicana.",
      highlights: ["Turismo de playa", "Recorridos gastronómicos", "Experiencia tequilera"],
      activities: ["Visita a museos", "recorridos gastronómicos", "fotografía urbana", "paseo en viñedos", "turismo de playa"],
      category: EventCategory.CULTURAL,
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2770
    },
    {
      name: "PalMar",
      location: "Mexico",
      date: new Date("2025-06-27"),
      music: [],
      city: "PalMar",
      country: "Mexico",
      startDate: new Date("2025-06-27"),
      endDate: new Date("2025-06-29"),
      description: "",
      highlights: [],
      activities: ["Playa", "convivencia", "networking", "fiesta"],
      category: EventCategory.BEACH,
      isHighlight: false,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2950
    },
    {
      name: "Valle de Guadalupe",
      location: "Baja California, Mexico",
      date: new Date("2025-07-03"),
      music: [],
      city: "Valle de Guadalupe",
      state: "Baja California",
      country: "Mexico",
      startDate: new Date("2025-07-03"),
      endDate: new Date("2025-07-06"),
      description: "Degusta vinos de clase mundial en las bodegas boutique del Valle de Guadalupe y disfruta de la gastronomía local en restaurantes de autor.",
      highlights: ["Paisajes de viñedos", "Degustación de vinos", "Cocina de autor"],
      activities: ["Catas de vino", "fotografía de viñedos", "turismo gastronómico", "recorridos por bodegas", "relajación"],
      category: EventCategory.CULTURAL,
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2680
    },
    {
      name: "Loreto",
      location: "Baja California Sur, Mexico",
      date: new Date("2025-07-10"),
      music: [],
      city: "Loreto",
      state: "Baja California Sur",
      country: "Mexico",
      startDate: new Date("2025-07-10"),
      endDate: new Date("2025-07-13"),
      description: "Navega por el Parque Nacional Bahía de Loreto y practica snorkel entre la diversa vida marina del 'Aquarium of the World'.",
      highlights: ["Playas tranquilas", "Snorkel y buceo", "Avistamiento de fauna marina"],
      activities: ["Snorkel", "senderismo", "observación de ballenas", "fotografía marina", "visitas culturales"],
      category: EventCategory.BEACH,
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2700
    },
    {
      name: "Merida",
      location: "Yucatán, Mexico",
      date: new Date("2025-07-17"),
      music: [],
      city: "Merida",
      state: "Yucatán",
      country: "Mexico",
      startDate: new Date("2025-07-17"),
      endDate: new Date("2025-07-20"),
      description: "Pasea por el elegante Paseo de Montejo, admirando las mansiones históricas, y explora los cercanos cenotes de aguas cristalinas.",
      highlights: ["Cultura colonial", "Cenotes", "Vida local auténtica"],
      activities: ["Visita a museos", "recorridos coloniales", "gastronomía yucateca", "fotografía arquitectónica", "tours culturales"],
      category: EventCategory.CULTURAL,
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2540
    },
    {
      name: "Oaxaca",
      location: "Oaxaca, Mexico",
      date: new Date("2025-07-24"),
      music: [],
      city: "Oaxaca",
      state: "Oaxaca",
      country: "Mexico",
      startDate: new Date("2025-07-24"),
      endDate: new Date("2025-07-27"),
      description: "Visita las cascadas petrificadas de Hierve el Agua y explora el sitio arqueológico de Monte Albán, cuna de la civilización zapoteca.",
      highlights: ["Paisajes naturales", "Sitios arqueológicos", "Gastronomía tradicional"],
      activities: ["Visita a mercados", "turismo cultural", "senderismo arqueológico", "fotografía de artesanías", "degustación de mezcal"],
      category: EventCategory.CULTURAL,
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2630
    },
    {
      name: "Tlaxcala",
      location: "Tlaxcala, Mexico",
      date: new Date("2025-07-24"),
      music: [],
      city: "Tlaxcala",
      state: "Tlaxcala",
      country: "Mexico",
      startDate: new Date("2025-07-24"),
      endDate: new Date("2025-07-27"),
      description: "Admira los murales históricos en el Palacio de Gobierno y visita el Santuario de las Luciérnagas durante la temporada de avistamiento.",
      highlights: ["Naturaleza estacional", "Arte y arquitectura", "Ruinas prehispánicas"],
      activities: ["Senderismo", "observación de luciérnagas (temporal)", "fotografía de naturaleza", "turismo histórico", "visita a haciendas"],
      category: EventCategory.NATURE,
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2790
    },
    {
      name: "Michoacan",
      location: "Michoacán, Mexico",
      date: new Date("2025-07-31"),
      music: [],
      city: "Michoacan",
      state: "Michoacán",
      country: "Mexico",
      startDate: new Date("2025-07-31"),
      endDate: new Date("2025-08-03"),
      description: "Sé testigo de la migración de la mariposa monarca en los santuarios de Michoacán y explora el pintoresco pueblo de Pátzcuaro.",
      highlights: ["Reservas naturales", "Festividades tradicionales", "Lagos y montañas"],
      activities: ["Avistamiento de mariposas", "visita a pueblos mágicos", "fotografía tradicional", "turismo religioso", "gastronomía local"],
      category: EventCategory.NATURE,
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2540
    },
    {
      name: "Jalisco",
      location: "Jalisco, Mexico",
      date: new Date("2025-08-07"),
      music: [],
      city: "Jalisco",
      state: "Jalisco",
      country: "Mexico",
      startDate: new Date("2025-08-07"),
      endDate: new Date("2025-08-10"),
      description: "Recorre los campos de agave en Tequila y disfruta de una cata en una destilería tradicional, descubriendo los secretos de esta emblemática bebida mexicana.",
      highlights: ["Turismo de playa", "Recorridos gastronómicos", "Experiencia tequilera"],
      activities: ["Visita a museos", "recorridos gastronómicos", "fotografía urbana", "paseo en viñedos", "turismo de playa"],
      category: EventCategory.CULTURAL,
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2770
    },
    {
      name: "Colombia",
      location: "Colombia",
      date: new Date("2025-08-16"),
      music: [],
      city: "Colombia",
      country: "Colombia",
      startDate: new Date("2025-08-16"),
      endDate: new Date("2025-08-22"),
      description: "Recorre la histórica Ciudad Amurallada de Cartagena y asciende al Cerro Monserrate en Bogotá para obtener vistas panorámicas de la capital colombiana.",
      highlights: ["Playas caribeñas", "Montañas verdes", "Pueblos con historia"],
      activities: ["Visita a museos", "caminatas urbanas", "turismo de naturaleza", "fotografía cultural", "actividades en playas y selvas"],
      category: EventCategory.CULTURAL,
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2770
    }
  ]

  for (const event of events) {
    await prisma.event.create({
      data: event
    })
  }

  console.log('Database has been seeded with events from the spreadsheet')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  }) 