const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

async function main() {
  // Clear existing events
  await prisma.event.deleteMany()

  // Seed events from the spreadsheet
  const events = [
    {
      name: "San Miguel de Allende",
      location: "Guanajuato, Mexico",
      city: "San Miguel de Allende",
      state: "Guanajuato",
      country: "Mexico",
      startDate: new Date("2025-04-17"),
      endDate: new Date("2025-04-20"),
      description: "Recorre las encantadoras calles empedradas de San Miguel de Allende y maravíllate con la arquitectura colonial de la Parroquia de San Miguel Arcángel.",
      highlights: ["Arquitectura colonial", "Calles empedradas", "Aguas termales"],
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2650,
      hotelAmenities: [],
      hotelIncludes: [],
      hotelExcludes: []
    },
    {
      name: "CDMX",
      location: "Ciudad de México, Mexico",
      city: "CDMX",
      state: "Ciudad de México",
      country: "Mexico",
      startDate: new Date("2025-04-24"),
      endDate: new Date("2025-04-27"),
      description: "Explora el imponente Zócalo y visita el Palacio de Bellas Artes, sumergiéndote en la vibrante escena artística y cultural de la capital mexicana.",
      highlights: ["Centro histórico", "Arte y cultura", "Parques urbanos"],
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2800,
      hotelAmenities: [],
      hotelIncludes: [],
      hotelExcludes: []
    },
    {
      name: "San Pedro Martir",
      location: "Baja California, Mexico",
      city: "San Pedro Martir",
      state: "Baja California",
      country: "Mexico",
      startDate: new Date("2025-04-25"),
      endDate: new Date("2025-04-27"),
      description: "Embárcate en una aventura de senderismo en la Sierra de San Pedro Mártir y visita el Observatorio Astronómico Nacional para una experiencia estelar única.",
      highlights: ["Senderismo de montaña", "Observación astronómica", "Vida silvestre"],
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2720,
      hotelAmenities: [],
      hotelIncludes: [],
      hotelExcludes: []
    },
    {
      name: "La Paz",
      location: "Baja California Sur, Mexico",
      city: "La Paz",
      state: "Baja California Sur",
      country: "Mexico",
      startDate: new Date("2025-05-01"),
      endDate: new Date("2025-05-04"),
      description: "Nada junto al majestuoso tiburón ballena en las aguas cristalinas de La Paz y relájate en las tranquilas playas de Balandra.",
      highlights: ["Playas vírgenes", "Nado con fauna marina", "Paseos en lancha"],
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2900,
      hotelAmenities: [],
      hotelIncludes: [],
      hotelExcludes: []
    },
    {
      name: "Chihuahua",
      location: "Chihuahua, Mexico",
      city: "Chihuahua",
      state: "Chihuahua",
      country: "Mexico",
      startDate: new Date("2025-05-09"),
      endDate: new Date("2025-05-12"),
      description: "Viaja en el legendario tren 'El Chepe' a través de las impresionantes Barrancas del Cobre y descubre la riqueza cultural de la Sierra Tarahumara.",
      highlights: ["Cañones impresionantes", "Rutas escénicas en tren", "Cultura indígena"],
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2670,
      hotelAmenities: [],
      hotelIncludes: [],
      hotelExcludes: []
    },
    {
      name: "Riviera Nayarit",
      location: "Nayarit, Mexico",
      city: "Riviera Nayarit",
      state: "Nayarit",
      country: "Mexico",
      startDate: new Date("2025-05-15"),
      endDate: new Date("2025-05-18"),
      description: "Surfea las olas de Sayulita y explora las Islas Marietas, hogar de la famosa Playa Escondida.",
      highlights: ["Playas paradisíacas", "Surf y deportes acuáticos", "Pueblos costeros"],
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2750,
      hotelAmenities: [],
      hotelIncludes: [],
      hotelExcludes: []
    },
    {
      name: "Hidalgo",
      location: "Hidalgo, Mexico",
      city: "Hidalgo",
      state: "Hidalgo",
      country: "Mexico",
      startDate: new Date("2025-05-22"),
      endDate: new Date("2025-05-25"),
      description: "Sumérgete en las aguas termales de las Grutas de Tolantongo y maravíllate con los Prismas Basálticos, formaciones geológicas únicas en su tipo.",
      highlights: ["Aguas termales", "Formaciones geológicas", "Pueblos tradicionales"],
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2600,
      hotelAmenities: [],
      hotelIncludes: [],
      hotelExcludes: []
    },
    {
      name: "Loreto",
      location: "Baja California Sur, Mexico",
      city: "Loreto",
      state: "Baja California Sur",
      country: "Mexico",
      startDate: new Date("2025-06-03"),
      endDate: new Date("2025-06-06"),
      description: "Navega por el Parque Nacional Bahía de Loreto y practica snorkel entre la diversa vida marina del 'Aquarium of the World'.",
      highlights: ["Playas tranquilas", "Snorkel y buceo", "Avistamiento de fauna marina"],
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2700,
      hotelAmenities: [],
      hotelIncludes: [],
      hotelExcludes: []
    },
    {
      name: "Jalisco",
      location: "Jalisco, Mexico",
      city: "Jalisco",
      state: "Jalisco",
      country: "Mexico",
      startDate: new Date("2025-06-12"),
      endDate: new Date("2025-06-15"),
      description: "Recorre los campos de agave en Tequila y disfruta de una cata en una destilería tradicional, descubriendo los secretos de esta emblemática bebida mexicana.",
      highlights: ["Turismo de playa", "Recorridos gastronómicos", "Experiencia tequilera"],
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2770,
      hotelAmenities: [],
      hotelIncludes: [],
      hotelExcludes: []
    },
    {
      name: "PalMar",
      location: "Mexico",
      city: "PalMar",
      country: "Mexico",
      startDate: new Date("2025-06-27"),
      endDate: new Date("2025-06-29"),
      description: "",
      highlights: [],
      isHighlight: false,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2950,
      hotelAmenities: [],
      hotelIncludes: [],
      hotelExcludes: []
    },
    {
      name: "Valle de Guadalupe",
      location: "Baja California, Mexico",
      city: "Valle de Guadalupe",
      state: "Baja California",
      country: "Mexico",
      startDate: new Date("2025-07-03"),
      endDate: new Date("2025-07-06"),
      description: "Degusta vinos de clase mundial en las bodegas boutique del Valle de Guadalupe y disfruta de la gastronomía local en restaurantes de autor.",
      highlights: ["Paisajes de viñedos", "Degustación de vinos", "Cocina de autor"],
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2680,
      hotelAmenities: [],
      hotelIncludes: [],
      hotelExcludes: []
    },
    {
      name: "Loreto",
      location: "Baja California Sur, Mexico",
      city: "Loreto",
      state: "Baja California Sur",
      country: "Mexico",
      startDate: new Date("2025-07-10"),
      endDate: new Date("2025-07-13"),
      description: "Navega por el Parque Nacional Bahía de Loreto y practica snorkel entre la diversa vida marina del 'Aquarium of the World'.",
      highlights: ["Playas tranquilas", "Snorkel y buceo", "Avistamiento de fauna marina"],
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2700,
      hotelAmenities: [],
      hotelIncludes: [],
      hotelExcludes: []
    },
    {
      name: "Merida",
      location: "Yucatán, Mexico",
      city: "Merida",
      state: "Yucatán",
      country: "Mexico",
      startDate: new Date("2025-07-17"),
      endDate: new Date("2025-07-20"),
      description: "Pasea por el elegante Paseo de Montejo, admirando las mansiones históricas, y explora los cercanos cenotes de aguas cristalinas.",
      highlights: ["Cultura colonial", "Cenotes", "Vida local auténtica"],
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2700,
      hotelAmenities: [],
      hotelIncludes: [],
      hotelExcludes: []
    },
    {
      name: "Oaxaca",
      location: "Oaxaca, Mexico",
      city: "Oaxaca",
      state: "Oaxaca",
      country: "Mexico",
      startDate: new Date("2025-07-24"),
      endDate: new Date("2025-07-27"),
      description: "Visita las cascadas petrificadas de Hierve el Agua y explora el sitio arqueológico de Monte Albán, cuna de la civilización zapoteca.",
      highlights: ["Paisajes naturales", "Sitios arqueológicos", "Gastronomía tradicional"],
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2630,
      hotelAmenities: [],
      hotelIncludes: [],
      hotelExcludes: []
    },
    {
      name: "Tlaxcala",
      location: "Tlaxcala, Mexico",
      city: "Tlaxcala",
      state: "Tlaxcala",
      country: "Mexico",
      startDate: new Date("2025-07-24"),
      endDate: new Date("2025-07-27"),
      description: "Admira los murales históricos en el Palacio de Gobierno y visita el Santuario de las Luciérnagas durante la temporada de avistamiento.",
      highlights: ["Naturaleza estacional", "Arte y arquitectura", "Ruinas prehispánicas"],
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2790,
      hotelAmenities: [],
      hotelIncludes: [],
      hotelExcludes: []
    },
    {
      name: "Michoacan",
      location: "Michoacán, Mexico",
      city: "Michoacan",
      state: "Michoacán",
      country: "Mexico",
      startDate: new Date("2025-07-31"),
      endDate: new Date("2025-08-03"),
      description: "Sé testigo de la migración de la mariposa monarca en los santuarios de Michoacán y explora el pintoresco pueblo de Pátzcuaro.",
      highlights: ["Reservas naturales", "Festividades tradicionales", "Lagos y montañas"],
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2540,
      hotelAmenities: [],
      hotelIncludes: [],
      hotelExcludes: []
    },
    {
      name: "Jalisco",
      location: "Jalisco, Mexico",
      city: "Jalisco",
      state: "Jalisco",
      country: "Mexico",
      startDate: new Date("2025-08-07"),
      endDate: new Date("2025-08-10"),
      description: "Recorre los campos de agave en Tequila y disfruta de una cata en una destilería tradicional, descubriendo los secretos de esta emblemática bebida mexicana.",
      highlights: ["Turismo de playa", "Recorridos gastronómicos", "Experiencia tequilera"],
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2770,
      hotelAmenities: [],
      hotelIncludes: [],
      hotelExcludes: []
    },
    {
      name: "Colombia",
      location: "Colombia",
      city: "Colombia",
      country: "Colombia",
      startDate: new Date("2025-08-16"),
      endDate: new Date("2025-08-22"),
      description: "Recorre la histórica Ciudad Amurallada de Cartagena y asciende al Cerro Monserrate en Bogotá para obtener vistas panorámicas de la capital colombiana.",
      highlights: ["Playas caribeñas", "Montañas verdes", "Pueblos con historia"],
      isHighlight: true,
      maxParticipants: 15,
      originalPrice: 10000,
      finalPrice: 2770,
      hotelAmenities: [],
      hotelIncludes: [],
      hotelExcludes: []
    }
  ]

  for (const event of events) {
    await prisma.event.create({
      data: event
    })
  }

  console.log('Database has been seeded with events from the spreadsheet')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  }) 